package com.example.weathersecurity.API.Model

data class Hour(
    val chance_of_rain: Int? = null,
    val chance_of_snow: Int? = null,
    val cloud: Int? = null,
    val condition: Condition? = null,
    val dewpoint_c: Double? = null,
    val dewpoint_f: Double? = null,
    val feelslike_c: Double? = null,
    val feelslike_f: Double? = null,
    val gust_kph: Double? = null,
    val gust_mph: Double? = null,
    val heatindex_c: Double? = null,
    val heatindex_f: Double? = null,
    val humidity: Int? = null,
    val is_day: Int? = null,
    val precip_in: Double? = null,
    val precip_mm: Double? = null,
    val pressure_in: Double? = null,
    val pressure_mb: Double? = null,
    val temp_c: Double? = null,
    val temp_f: Double? = null,
    val time: String? = null,
    val time_epoch: Int? = null,
    val uv: Double? = null,
    val vis_km: Double? = null,
    val vis_miles: Double? = null,
    val will_it_rain: Int? = null,
    val will_it_snow: Int? = null,
    val wind_degree: Int? = null,
    val wind_dir: String? = null,
    val wind_kph: Double? = null,
    val wind_mph: Double? = null,
    val windchill_c: Double? = null,
    val windchill_f: Double? = null
)